#include <catch2/catch_test_macros.hpp>
#include <regex>

#include <fe/config.hpp>

// config.hpp is generated by CMake's configure_file() from
// include/config.hpp.template, substituting @FE_VERSION@ (read from
// package.json) and @FE_COMMIT_HASH@ (from `git rev-parse --short HEAD`).
// These tests check the substitution actually happened and the pieces
// combine the way versionString() documents - not any specific version
// number, so they don't need updating when the version bumps.

TEST_CASE("fe::version() is a substituted semver string, not the raw placeholder", "[config]"){
    auto v = fe::version();
    REQUIRE_FALSE(v.empty());
    REQUIRE(v != "@FE_VERSION@");
    // major.minor.patch, optionally with a -prerelease/+build suffix.
    std::regex semverLike(R"(^\d+\.\d+\.\d+.*$)");
    REQUIRE(std::regex_match(v, semverLike));
}

TEST_CASE("fe::commitHash() is either a short git hash or the documented fallback", "[config]"){
    auto h = fe::commitHash();
    REQUIRE_FALSE(h.empty());
    REQUIRE(h != "@FE_COMMIT_HASH@");
    if(h != "unknown"){
        // short hashes are typically 7-12 lowercase hex chars.
        std::regex hexLike(R"(^[0-9a-f]{4,40}$)");
        REQUIRE(std::regex_match(h, hexLike));
    }
}

TEST_CASE("fe::versionString() joins version and commitHash with '+' (SemVer build metadata)", "[config]"){
    REQUIRE(fe::versionString() == (fe::version() + "+" + fe::commitHash()));
}
