name: cd
on:
  push:
    branches:
      - master
jobs:
  cd:
    name: deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name: build dist and deploy
        shell: bash
        env:
            GITUSER: ${{secrets.GITUSER}}
            EMAIL: ${{secrets.EMAIL}}
            PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}
        run: |
          bash .devops/dist.sh && sh .devops/deploy.sh $GITUSER $EMAIL
