name: pkg

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  npm:
    name: build + publish to npm and ghp
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - name: checkout branch
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.tag_name || '' }}

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: update npm
        run: npm install --global npm@latest

      - name: build dist
        run: |
          npm ci --ignore-scripts
          npm run prep
          npm run build

      - name: test JavaScript
        run: npm test

      - name: install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: test e2e
        run: npm run test:e2e

      - name: publish to npm and github packages
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .devops/publish.sh "$GH_TOKEN"
